from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardButton, InlineKeyboardMarkup

add_klient_base = KeyboardButton('Клиент кошиш')
remove_klient_base = KeyboardButton("Клиент очириш")
info_klient_base = KeyboardButton("Клиент хакида малумот")
location_klient_base = KeyboardButton("Турган жойингизни локатсиясини критинг")
remake_klient_base = KeyboardButton("Клиент малумотини озгартириш")

add_viloyat_1 = InlineKeyboardButton("Qoraqalpogʻiston", callback_data= "av_1")
add_viloyat_2 = InlineKeyboardButton("Buxoro",callback_data= "av_2")
add_viloyat_3 = InlineKeyboardButton("Fargʻona",callback_data= "av_3")
add_viloyat_4 = InlineKeyboardButton("Jizzax",callback_data= "av_4")
add_viloyat_5 = InlineKeyboardButton("Xorazm",callback_data= "av_5")
add_viloyat_6 = InlineKeyboardButton("Namangan",callback_data= "av_6")
add_viloyat_7 = InlineKeyboardButton("Navoiy",callback_data= "av_7")
add_viloyat_8 = InlineKeyboardButton("Qashqadaryo",callback_data= "av_8")
add_viloyat_9 = InlineKeyboardButton("Andijon",callback_data= "av_9")
add_viloyat_10 = InlineKeyboardButton("Samarqand",callback_data= "av_10")
add_viloyat_11= InlineKeyboardButton("Sirdaryo",callback_data= "av_11")
add_viloyat_12= InlineKeyboardButton("Surxondaryo",callback_data= "av_12")
back = InlineKeyboardButton('Back', callback_data='back')


add2_viloyat_1 = KeyboardButton("Qoraqalpogʻiston",)
add2_viloyat_2 = KeyboardButton("Buxoro")
add2_viloyat_3 = KeyboardButton("Fargʻona")
add2_viloyat_4 = KeyboardButton("Jizzax")
add2_viloyat_5 = KeyboardButton("Xorazm")
add2_viloyat_6 = KeyboardButton("Namangan")
add2_viloyat_7 = KeyboardButton("Navoiy")
add2_viloyat_8 = KeyboardButton("Qashqadaryo")
add2_viloyat_9 = KeyboardButton("Andijon")
add2_viloyat_10 = KeyboardButton("Samarqand",)
add2_viloyat_11= KeyboardButton("Sirdaryo",)
add2_viloyat_12= KeyboardButton("Surxondaryo",)



remove_1_viloyat = InlineKeyboardButton("Qoraqalpogʻiston Respublikasi",callback_data= "rv_1")
remove_2_viloyat = InlineKeyboardButton("Buxoro viloyati",callback_data= "rv_2")
remove_3_viloyat = InlineKeyboardButton("Fargʻona  viloyati",callback_data= "rv_3")
remove_4_viloyat = InlineKeyboardButton("Jizzax viloyati",callback_data= "rv_4")
remove_5_viloyat = InlineKeyboardButton("Xorazm viloyati",callback_data= "rv_5")
remove_6_viloyat = InlineKeyboardButton("Namangan viloyati",callback_data= "rv_6")
remove_7_viloyat = InlineKeyboardButton("Navoiy viloyati",callback_data= "rv_7")
remove_8_viloyat = InlineKeyboardButton("Qashqadaryo viloyati",callback_data= "rv_8")
remove_9_viloyat = InlineKeyboardButton("Andijon viloyati",callback_data= "rv_9")
remove_10_viloyat = InlineKeyboardButton("Samarqand viloyati",callback_data= "rv_10")
remove_11_viloyat= InlineKeyboardButton("Sirdaryo viloyati",callback_data= "rv_11")
remove_12_viloyat= InlineKeyboardButton("Surxondaryo viloyati",callback_data= "rv_12")


info_1_viloyat = InlineKeyboardButton("Qoraqalpogʻiston Respublikasi",callback_data= "1v_1")
info_2_viloyat = InlineKeyboardButton("Buxoro viloyati",callback_data= "1v_2")
info_3_viloyat = InlineKeyboardButton("Fargʻona  viloyati",callback_data= "1v_3")
info_4_viloyat = InlineKeyboardButton("Jizzax viloyati",callback_data= "1v_4")
info_5_viloyat = InlineKeyboardButton("Xorazm viloyati",callback_data= "1v_5")
info_6_viloyat = InlineKeyboardButton("Namangan viloyati",callback_data= "1v_6")
info_7_viloyat = InlineKeyboardButton("Navoiy viloyati",callback_data= "1v_7")
info_8_viloyat = InlineKeyboardButton("Qashqadaryo viloyati",callback_data= "1v_8")
info_9_viloyat = InlineKeyboardButton("Andijon viloyati",callback_data= "1v_9")
info_10_viloyat = InlineKeyboardButton("Samarqand viloyati",callback_data= "1v_10")
info_11_viloyat= InlineKeyboardButton("Sirdaryo viloyati",callback_data= "1v_11")
info_12_viloyat= InlineKeyboardButton("Surxondaryo viloyati",callback_data= "1v_12")


remake_1_viloyat = InlineKeyboardButton("Qoraqalpogʻiston",callback_data= "rev_1")
remake_2_viloyat = InlineKeyboardButton("Buxoro",callback_data= "rev_2")
remake_3_viloyat = InlineKeyboardButton("Fargʻona",callback_data= "rev_3")
remake_4_viloyat = InlineKeyboardButton("Jizzax",callback_data= "rev_4")
remake_5_viloyat = InlineKeyboardButton("Xorazm",callback_data= "rev_5")
remake_6_viloyat = InlineKeyboardButton("Namangan",callback_data= "rev_6")
remake_7_viloyat = InlineKeyboardButton("Navoiy",callback_data= "rev_7")
remake_8_viloyat = InlineKeyboardButton("Qashqadaryo",callback_data= "rev_8")
remake_9_viloyat = InlineKeyboardButton("Andijon",callback_data= "rev_9")
remake_10_viloyat = InlineKeyboardButton("Samarqand",callback_data= "rev_10")
remake_11_viloyat= InlineKeyboardButton("Sirdaryo",callback_data= "rev_11")
remake_12_viloyat= InlineKeyboardButton("Surxondaryo",callback_data= "rev_12")

markup = ReplyKeyboardMarkup(resize_keyboard=True).add(KeyboardButton("Lokatsiya", request_location=True))

########################################## REPLY ##############################################
main_menu = ReplyKeyboardMarkup(resize_keyboard= True)
main_menu.add(add_klient_base)
main_menu.add(remove_klient_base)
main_menu.add(info_klient_base)
main_menu.add(location_klient_base)
main_menu.add(remake_klient_base)

add_malumot = InlineKeyboardMarkup(row_width = 2)
add_malumot.insert(add_viloyat_1)
add_malumot.insert(add_viloyat_2)
add_malumot.insert(add_viloyat_3)
add_malumot.insert(add_viloyat_4)
add_malumot.insert(add_viloyat_5)
add_malumot.insert(add_viloyat_6)
add_malumot.insert(add_viloyat_7)
add_malumot.insert(add_viloyat_8)
add_malumot.insert(add_viloyat_9)
add_malumot.insert(add_viloyat_10)
add_malumot.insert(add_viloyat_11)
add_malumot.insert(add_viloyat_12)

add2_malumot = ReplyKeyboardMarkup(resize_keyboard= True)
add2_malumot.add(add2_viloyat_1)
add2_malumot.add(add2_viloyat_2)
add2_malumot.add(add2_viloyat_3)
add2_malumot.add(add2_viloyat_4)
add2_malumot.add(add2_viloyat_5)
add2_malumot.add(add2_viloyat_6)
add2_malumot.add(add2_viloyat_7)
add2_malumot.add(add2_viloyat_8)
add2_malumot.add(add2_viloyat_9)
add2_malumot.add(add2_viloyat_10)
add2_malumot.add(add2_viloyat_11)
add2_malumot.add(add2_viloyat_12)


remove_malumot = InlineKeyboardMarkup(row_width = 2)
remove_malumot.insert(add_viloyat_1)
remove_malumot.insert(add_viloyat_2)
remove_malumot.insert(add_viloyat_3)
remove_malumot.insert(add_viloyat_4)
remove_malumot.insert(add_viloyat_5)
remove_malumot.insert(add_viloyat_6)
remove_malumot.insert(add_viloyat_7)
remove_malumot.insert(add_viloyat_8)
remove_malumot.insert(add_viloyat_9)
remove_malumot.insert(add_viloyat_10)
remove_malumot.insert(add_viloyat_11)
remove_malumot.insert(add_viloyat_12)
remove_malumot.insert(back)



info_malumot = InlineKeyboardMarkup(row_width = 2)
info_malumot.insert(add_viloyat_1)
info_malumot.insert(add_viloyat_2)
info_malumot.insert(add_viloyat_3)
info_malumot.insert(add_viloyat_4)
info_malumot.insert(add_viloyat_5)
info_malumot.insert(add_viloyat_6)
info_malumot.insert(add_viloyat_7)
info_malumot.insert(add_viloyat_8)
info_malumot.insert(add_viloyat_9)
info_malumot.insert(add_viloyat_10)
info_malumot.insert(add_viloyat_11)
info_malumot.insert(add_viloyat_12)
info_malumot.insert(back)


remake_malumot = InlineKeyboardMarkup(row_width = 2)
remake_malumot.insert(add_viloyat_1)
remake_malumot.insert(add_viloyat_2)
remake_malumot.insert(add_viloyat_3)
remake_malumot.insert(add_viloyat_4)
remake_malumot.insert(add_viloyat_5)
remake_malumot.insert(add_viloyat_6)
remake_malumot.insert(add_viloyat_7)
remake_malumot.insert(add_viloyat_8)
remake_malumot.insert(add_viloyat_9)
remake_malumot.insert(add_viloyat_10)
remake_malumot.insert(add_viloyat_11)
remake_malumot.insert(add_viloyat_12)
remake_malumot.insert(back)










location = ReplyKeyboardMarkup( resize_keyboard=True ).add( KeyboardButton("Lokatsiya", request_location=True) )